apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vllkdb80n-dotnet-basic
  janus-idp.io/tekton: vllkdb80n-dotnet-basic
  backstage.io/kubernetes-id: vllkdb80n-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vllkdb80n-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
